---
- name: restart nginx docker
  when: nginx_run_as is defined and nginx_run_as=="docker" and disablenotify!=true
  docker_compose:
    project_src: "{{ user_path }}/{{ deploy_name }}"
    restarted: yes

- name: restart nginx service
  when: nginx_run_as is defined and nginx_run_as=="service" and disablenotify!=true
  service:
    name: "{{ deploy_name }}"
    state: restarted

- name: restart nginx stack
  when: nginx_run_as is defined and nginx_run_as=="stack" and disablenotify!=true
  docker_stack:
    state: present
    prune: yes
    name: "{{ deploy_name }}"
    compose:
      - "{{ user_path }}/{{ deploy_name }}/docker-compose.yml"