NGINX := $$(docker ps -a | grep "Up" | awk '{print $$NF}' | grep -w "{{ nginx_stack }}_nginx-proxy\.*")

reload:
	docker exec -i $(NGINX) nginx -s reload

rm:
	docker stack rm {{ deploy_name }}

deploy:
	docker stack deploy -c docker-compose.yml {{ deploy_name }}

ps:
	docker stack ps {{ deploy_name }} --no-trunc

log:
	docker service logs -f $(NGINX)

exec:
	docker exec -it $(NGINX) /bin/bash

	